{% set version = '0.0.2' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rcppint64
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/RcppInt64_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/RcppInt64/RcppInt64_{{ version }}.tar.gz
  sha256: c38be311d655728e8df96b741cbe68d6e8f1e5cb7fdee1fab8370414b166c849

build:
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  # This is needed to suppress a warning about R.dll not being found
  missing_dso_whitelist:
    - '*/R.dll'            # [win]

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-rcpp >=1.0.8
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-rcpp >=1.0.8

test:
  requires:
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}make
    - r-bit64
    - r-tinytest
  commands:
    - Rscript -e "library('RcppInt64')"
    - Rscript -e "tinytest::test_package('RcppInt64')"

about:
  home: https://github.com/eddelbuettel/rcppint64
  license: GPL-2.0-or-later
  summary: >-
    "'Int64' values can be created and accessed via the 'bit64' package and its
    'integer64' class which package the 'int64' representation cleverly into a
    'double'. This packages helps conversions between 'R' and 'C++' via several
    helper functions provided via a single header file. A complete example
    client package is included as an illustration."
  license_family: GPL2
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r
    - jdblischak

# Package: RcppInt64
# Type: Package
# Title: 'Rcpp'-Based Helper Functions to Pass 'Int64' Values Between 'R' and 'C++'
# Version: 0.0.2
# Date: 2023-09-12
# Authors@R: c(person(given = "Dirk", family = "Eddelbuettel", role = c("aut", "cre"), email = "edd@debian.org", comment = c(ORCID = "0000-0001-6419-907X")))
# Description: 'Int64' values can be created and accessed via the 'bit64' package and its 'integer64' class which package the 'int64' representation cleverly into a 'double'. This packages helps conversions between 'R' and 'C++' via several helper functions provided via a single header file. A complete example client package is included as an illustration.
# URL: https://github.com/eddelbuettel/rcppint64
# BugReports: https://github.com/eddelbuettel/rcppint64/issues
# License: GPL (>= 2)
# Imports: Rcpp (>= 1.0.8)
# LinkingTo: Rcpp
# Suggests: tinytest, bit64
# RoxygenNote: 6.0.1
# Encoding: UTF-8
# NeedsCompilation: yes
# Packaged: 2023-09-12 12:04:50 UTC; edd
# Author: Dirk Eddelbuettel [aut, cre] (<https://orcid.org/0000-0001-6419-907X>)
# Maintainer: Dirk Eddelbuettel <edd@debian.org>
# Repository: CRAN
# Date/Publication: 2023-09-12 17:20:02 UTC
